site_name: Compose Navigation Reimagined
site_description: "Type-safe navigation library for Jetpack Compose"
site_author: "Vitali Olshevski"
site_url: "https://olshevski.github.io/compose-navigation-reimagined"
edit_uri: ""
copyright: Copyright &copy; 2022-2023 Vitali Olshevski
repo_name: "olshevski/compose-navigation-reimagined"
repo_url: "https://github.com/olshevski/compose-navigation-reimagined"

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.expand
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/olshevski
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/olshevski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/olshevski_dev
    - icon: fontawesome/solid/envelope
      link: mailto:tech@olshevski.dev

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - index.md
  - nav-controller.md
  - "NavHost":
    - "Basics": nav-host.md
    - animations.md
    - dialogs.md
    - bottom-sheets.md
  - back-handling.md
  - nested-navigation.md
  - "ViewModels":
    - "Entry-scoped": view-models.md
    - "Shared": shared-view-models.md
  - return-results.md
